- name: Directories are created
  file:
    path: "{{ item.dir }}"
    mode: 0777
    recurse: yes
    state: directory
  with_items: configs
  tags: [jenkins]

- name: Container is running
  docker:
    name: jenkins
    image: jenkins
    ports: 8080:8080
    volumes:
      - /data/jenkins:/var/jenkins_home
      - /vagrant/.vagrant/machines:/machines
  register: container_result
  tags: [jenkins]

- pause: seconds=30
  when: container_result|changed
  tags: [jenkins]

- name: Configurations are present
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dir }}/{{ item.file }}"
    mode: 0777
  with_items: configs
  register: configs_result
  tags: [jenkins]

- name: Plugins are installed
  shell: "curl -X POST \
    -d '<jenkins><install plugin=\"{{ item }}@latest\" /></jenkins>' \
    --header 'Content-Type: text/xml' \
    http://{{ ip }}:8080/pluginManager/installNecessaryPlugins"
  args:
    creates: /data/jenkins/plugins/{{ item }}
  with_items: plugins
  register: plugins_result
  tags: [jenkins]

- wait_for:
    path: /data/jenkins/plugins/{{ item }}
  with_items: plugins

- name: Container is restarted
  docker:
    name: jenkins
    image: jenkins
    state: restarted
  when: configs_result|changed or plugins_result|changed
  tags: [jenkins]

- pause: seconds=30
  when: configs_result|changed or plugins_result|changed

- name: Job directories are present
  file:
    path: "{{ home }}/jobs/{{ item.name }}"
    state: directory
    mode: 0777
  with_items: jobs
  tags: [jenkins]

- name: Jobs are present
  template:
    src: "{{ item.src }}"
    dest: "{{ home }}/jobs/{{ item.name }}/config.xml"
    mode: 0777
  with_items: jobs
  register: jobs_result
  tags: [jenkins]

- name: Jenkins is reloaded
  uri:
    url: http://{{ ip }}:8080/reload
    method: POST
    status_code: 200,302
  when: jobs_result|changed
  ignore_errors: yes
  tags: [jenkins]

- name: Scripts are present
  copy:
    src: scripts
    dest: /data
    mode: 0766
  tags: [jenkins]
