- name: Directories are present
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /data
    - /data/registry
  tags: [registry]

- name: Container is running
  docker:
    name: registry
    image: registry:2
    ports: 5000:5000
    volumes:
      - /vagrant/registry:/var/lib/registry/docker/registry
  tags: [registry]
