- name: Container is running
  docker:
    name: "{{ registrator_name }}"
    image: "{{ registry_url }}registrator"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    hostname: "{{ ansible_hostname }}"
    command: -ip {{ facter_ipaddress_eth1 }} {{ registrator_protocol }}://{{ facter_ipaddress_eth1 }}:{{ registrator_port }}
  tags: [etcd]
