- hosts: swarm
  remote_user: vagrant
  serial: 1
  vars:
    - debian_version: wily
    - docker_cfg_dest: /lib/systemd/system/docker.service
    - is_systemd: true
    - skip_ui: true
  roles:
    - common
    - rsyslog
    - docker
    - consul
    - consul-template
    - swarm
    - registrator
